### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by mrchypark** [jcrodriguez1989/autokeras#4]
autokeras is now 0.4.0 .

autokeras 0.3.7 is depends tensorflow==1.12.0 but it's removed on pip or conda.

need to upgrade.

**Comment by mrchypark** [comment]
Oh, same issues closed. sorry

**Comment by laresbernardo** [comment]
I'm getting the following error when trying to install:
´Error in virtualenv_install(envname, packages, ...) : 
  unused arguments (python_version = conda_python_version, pip = TRUE, pip_ignore_installed = FALSE´

**Comment by jcrodriguez1989** [comment]
Please could you try doing:

```r
update.packages() # will update packages, particularly `reticulate`
remotes::install_github("jcrodriguez1989/autokeras")
autokeras::install_autokeras()
```

**Comment by laresbernardo** [comment]
Thanks for your reply. I updated `reiticulate` and now get this error when running `install_autokeras()`.
```
Creating virtual environment '~/.virtualenvs/r-reticulate' ...
Using python: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
sh: /Users/bernardo/.virtualenvs/r-reticulate/bin/pip: No such file or directory
Error: Error installing package(s): 'pip', 'wheel', 'setuptools'
In addition: Warning message:
In system2(pip, args) : error in running command
```
Any idea why? Does it has anything to do with `pip` instead of `pip3` or something like that?

**Comment by jcrodriguez1989** [comment]
I don't really know where your issue comes from.
Does it work if you try to install keras?
```r
remotes::install_github("rstudio/keras")
library(keras)
install_keras()
```

**Comment by laresbernardo** [comment]
Exactly the same error. Could it be a directory route issue?

**Comment by jcrodriguez1989** [comment]
Ok, so then, it might be an issue related to `reticulate`.
I guess people in the `keras` or `reticulate` packages could help you better than me.

Sorry but I've never seen that issue before.

**Comment by laresbernardo** [comment]
Thanks for your quick and useful answers. I'll try to fix it and will let you know what works for me.

**Comment by laresbernardo** [comment]
Same issue [here](https://stackoverflow.com/questions/57936588/error-installing-tensorflow-in-r-users-emmeran-virtualenvs-r-reticulate-bin-p) as well, but no solution provided

**Comment by laresbernardo** [comment]
Well, this worked even though it is not an elegant solution:
I copied the `pip` file from another `.virtualenvs` I found and pasted it into the `r-reticulate/bin` folder. Now at least it's running and got another different error!
New error: `Error: Error installing package(s): 'tensorflow==2.1.0', 'keras', 'autokeras==1.0.1', 'h5py', 'pyyaml', 'requests', 'Pillow', 'scipy'`
